# ------------------------------------------------------------------------------
# Build stage
# ------------------------------------------------------------------------------
FROM node:18-alpine as builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

CMD ["yarn", "start:dev"]
